// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGmqpymvchYcMxsV7oJsk1VpvjbZIqp10',
    appId: '1:984724570156:web:bd32df624e7b5535559189',
    messagingSenderId: '984724570156',
    projectId: 'jrfvhub',
    authDomain: 'jrfvhub.firebaseapp.com',
    storageBucket: 'jrfvhub.firebasestorage.app',
    measurementId: 'G-EKR6RLRCWT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvfL21jqBSD0hjyfIbqmR7R1YTH-rCTwY',
    appId: '1:984724570156:android:f09294bf7dfc0378559189',
    messagingSenderId: '984724570156',
    projectId: 'jrfvhub',
    storageBucket: 'jrfvhub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaLyrSYMpVh0gXBLtpUhTVZzcWzPGJROs',
    appId: '1:984724570156:ios:52d4e5521dd435d0559189',
    messagingSenderId: '984724570156',
    projectId: 'jrfvhub',
    storageBucket: 'jrfvhub.firebasestorage.app',
    iosBundleId: 'com.example.jrfvhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaLyrSYMpVh0gXBLtpUhTVZzcWzPGJROs',
    appId: '1:984724570156:ios:52d4e5521dd435d0559189',
    messagingSenderId: '984724570156',
    projectId: 'jrfvhub',
    storageBucket: 'jrfvhub.firebasestorage.app',
    iosBundleId: 'com.example.jrfvhub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGmqpymvchYcMxsV7oJsk1VpvjbZIqp10',
    appId: '1:984724570156:web:f85d4fde802220e2559189',
    messagingSenderId: '984724570156',
    projectId: 'jrfvhub',
    authDomain: 'jrfvhub.firebaseapp.com',
    storageBucket: 'jrfvhub.firebasestorage.app',
    measurementId: 'G-J4VM2ZM94G',
  );
}
